id: 0x74
name: mission
description: controls the general procedures of the mission

#structs:

threads:
  missionThread:
    firstRun: 1000_ms
    period: 1000_ms
    priority: 9000

subscribe:
  attitudeDeterminationTopic: direct
  proximityTopic: direct
  lightSensorTopic: direct
  missionModeTopic: direct

publish:
  - modeTopic


telecommands:
  NOP:
    id: 1
  ChangeMode:
    id: 2
    fields:
      modes:
        type: uint8_t
        aliases:
          0: Stop
          1: Find
          2: Pointsun
          3: pointasteroid
          4: reflect
          5: everything
    description: |
      ### Changes the overarcing mode of the satellite

      * Stop: stops current rotation 
      * Find: spins around and finds the brightest point
      * Pointsun: points at where it thinks the sun is. if we havent found it yet finds it
      * pointasteroid: points at where it thinks the asteroid is. if we havent found it yet finds it
      * reflect: reflects the light from the sun to the asteroid if we havent found the asteroid or sun yet finds it
      * everything: finds the sun and asteroid and reflects the light onto the asteroid
  SetMinDist:
    id: 6
    fields:
      dist: float
  ChangeAngle:
    id: 3
    fields:
      setangle:
        type: uint8_t
    description: Angle that the mirror has. minimum 0° maximum 90 °  but over ~ 45 ° has an effect on the center of gravity
  SetSunConstants:
    id: 4
    fields:
      height:
        type: uint32_t
      distance:
        type: uint32_t
  SetRotationSpeed:
    id: 5
    fields:
      speed:
        type: uint32_t
    description: "sets the rotation speed of the satellite while finding the sun / asteroid"


standard_telemetry:
    currentAngle: uint8_t
    currentMode: uint8_t
    isInMission: bool
    attitudeLight: float
    attitudeObject: float
    distanceObject: float
    intensityLight: float
    testvar1: float
    testvar2: float



