name: FloatSat

ground:
  eventTopic: corfu::eventTopic
  telemetryTopic: radioDownTopic # corfu::downlinkTelemetryTopic -> CAUSES GENERATOR ERROR
  telecommandTopic: radioUpTopic # corfu::uplinkTelecommandTopic -> CAUSES GENERATOR ERROR
  downlinkPort: 8671
  uplinkPort: 8672
  standardTelemetry:
    app: housekeeper
    subserviceId: 1

drivers:
  vl53l4ed: default
  lsm9ds1: default

topics:
  biasOffsetTopic:
    id: 5761
    fields:
      offset: float
  radioUpTopic: # for tests only
    id: 2337
    type: corfu::Telecommand
  radioDownTopic: # for tests only
    id: 2447
    type: corfu::Telemetry
  isStableTopic:
    id: 2556
    description: If the sat is stable now, ie, if we have a lot of velocity on any axis
    fields:
      is_stable: bool
  attitudeDeterminationTopic:
    id: 1001
    description: Where we are, and how fast we are, right now
    fields:
      position: float
      velocity: float
  desiredMotorSpeedTopic:
    id: 1002
    description: speed in RPM
    fields:
      speed: float
  desiredStateValueTopic:
    id: 1004
    description: either Rotation speed, or angel, depending on mode
    fields:
      value: float
  peripheralOnOffTopic:
    id: 1005
    description: bit Array of on off
    fields:
      state:
        bit_array:
          length: 3

  imuDataTopic:
    id: 2001
    description: IMU data accelerometer[3] + gyro[3] + magentometer[3]
    fields:
      accelerometer:
        array:
          length: 3
          type: float
      gyroscope:
        array:
          length: 3
          type: float
      magnetometer:
        array:
          length: 3
          type: float
  lightSensorTopic:
    id: 6001
    description: contains the intensity of the light recieved by the light sensor
    fields:
      intensity: float
  proximityTopic:
    id: 7001
    description: contains the output of the proximity sensor
    fields:
      distance: float
  modeTopic:
    id: 8001
    description: the current satellite mode and submode
    fields:
      mode: uint8_t
      submode: uint8_t
  missionModeTopic:
    id: 8002
    description: the current part of the mission that is active
    fields:
      mode: uint8_t
  solarCellForbiddenTopic:
    id: 6666
    description: you shall not solar cell
    fields:
      is_forbidden: bool
