if(EXISTS "/home/jonathanerhard/Projects/floatSat/build-corfu-host-tools/libs/libcorfu-config-parser/test/libcorfu-config-parser-test[1]_tests.cmake")
  include("/home/jonathanerhard/Projects/floatSat/build-corfu-host-tools/libs/libcorfu-config-parser/test/libcorfu-config-parser-test[1]_tests.cmake")
else()
  add_test(libcorfu-config-parser-test_NOT_BUILT libcorfu-config-parser-test_NOT_BUILT)
endif()
