id: 0x02
name: power
description: change this to whatever you want

threads:
  mainthread:
    firstRun: 1000_ms
    period: 100_ms
    priority: 10

publish:
  - powerTopic

telecommands:
  NOP:
    id: 1

standard_telemetry:
    voltage:
      type: float 
      customWidget: plottingWidget
    current:
      type: float 
      customWidget: plottingWidget