id: 0x79
name: reader
description: reads out the IMU (and possibly other stuff)

#structs:

threads:
  readthreat:
    firstRun: 100_ms
    period: 100_ms
    priority: 120


#subscribe:
#  exampleTopic1: direct


publish:
  - imuDataTopic
  - corfu::appIsAliveTopic
  - corfu::anomalyTopic
#  - corfu::extendedTelemetryTopic

telecommands:
  NOP:
    id: 1

#  ExampleWithFields:
#    id: 2
#    fields:
#      parameter: uint8_t

standard_telemetry:
    appStatus: uint8_t

#extended_telemetry:
#  exampleETX:
#    id: 1
#    fields:
#      number: uint8_t

#anomalies:

