id: 0x20
name: sensors
description: publishes sensor data

threads:
  collectData:
    firstRun: 100_ms
    period: 10_ms
    priority: 1000

publish:
  - imuDataTopic
  - proximityTopic
  - lightSensorTopic
  - corfu::appIsAliveTopic
  - corfu::anomalyTopic
  - corfu::extendedTelemetryTopic
  - corfu::standardTelemetryTopic

subscribe:
  calibMagTopic: default

telecommands:
  NOP:
    id: 1
  CalibGyro:
    id: 2

standard_telemetry:
    roll: float
    pitch: float
    yaw: float
    ax: float
    ay: float
    az: float
    mx: float
    my: float
    mz: float
    distance:
      type: float 
      customWidget: plottingWidget
    brightness:
      type: float 
      customWidget: plottingWidget
    magx0: int16_t
    magx1: int16_t
    magy0: int16_t
    magy1: int16_t
    magz0: int16_t
    magz1: int16_t