id: 0x03
name: solar-array-control
description: controlls the position of the movable solar arrays

threads:
  solarArrayLerpThread:
    firstRun: 1000_ms
    period: 50_ms
    priority: 120

subscribe:
  attitudeDeterminationTopic: direct
  sunPositionTopic: direct
  modeTopic: direct
  isStableTopic: direct
  solarCellForbiddenTopic: direct

publish:
  - corfu::appIsAliveTopic #might not be neeed without thread

telecommands:
  NOP:
    id: 1
  SetServoAngle:
    id: 2
    fields:
      angle: 
        type: float
        min: -85.0
        max: 85.0
  UnsetManualOverride:
    id: 3
  StableNeeded:
    id: 4
    fields:
      is_needed: bool

standard_telemetry:
  sunPosition: float
  status:
    type: uint8_t
    aliases:
      0: retracted
      1: extended-fixed
      2: extended-moving
  angle: float
  manualOverride: bool