id: 0x68
name: adcs
description: Attitude Determination and Control

#structs:

threads:
  adcsThreat:
    firstRun: 1100_ms
    period: 10_ms
    priority: 1200
    stackSize: 6000

subscribe:
  imuDataTopic: direct
  modeTopic: direct
  

publish:
  - attitudeDeterminationTopic
  - isStableTopic
#  - corfu::appIsAliveTopic
#  - corfu::anomalyTopic
#  - corfu::extendedTelemetryTopic

telecommands:
  NOP:
    id: 1
  SetControlMode:
    id: 2
    fields:
      mode:
        type: uint8_t
        aliases:
          0: Nothing
          1: Position
          2: Velocity
      submode:
        type: uint8_t
    description: |
      ### changes the position / velocity of the satellite

      * Noting: keeps the current position
      * Position: aligns the attitude to the in submode specified attitude
      * Velocity: changes the desired velocity to the in submode specified attitude
  SafePowerUpDown:
    id: 3
    description: changes the satellites flywheel from 0 to 2500 RPM and back


#  ExampleWithFields:
#    id: 2
#    fields:
#      parameter: uint8_t

standard_telemetry:
    attitudeYaw: float
    pitch: float
    roll: float
    speed: float
    target_att: float
    target_speed: float
    motor_speed: float


#extended_telemetry:
#  exampleETX:
#    id: 1
#    fields:
#      number: uint8_t

#anomalies:

