id: 0x68
name: adcs
description: Attitude Determination and Control

#structs:

threads:
  examplethread:
    firstRun: 1100_ms
    period: 100_ms
    priority: 120

subscribe:
  imuDataTopic: direct
  modeTopic: direct
  

publish:
  - attitudeDeterminationTopic
  - isStableTopic
#  - corfu::appIsAliveTopic
#  - corfu::anomalyTopic
#  - corfu::extendedTelemetryTopic

telecommands:
  NOP:
    id: 1
  SetControlMode:
    id: 2
    fields:
      mode:
        type: uint8_t
        aliases:
          0: Nothing
          1: Velocity
          2: Position

#  ExampleWithFields:
#    id: 2
#    fields:
#      parameter: uint8_t

standard_telemetry:
    appStatus: uint8_t
    roll: float
    pitch: float
    yaw: float

#extended_telemetry:
#  exampleETX:
#    id: 1
#    fields:
#      number: uint8_t

#anomalies:

