id: 0x68
name: adcs
description: Attitude Determination and Control

#structs:

threads:
  adcsThreat:
    firstRun: 1100_ms
    period: 100_ms
    priority: 1200
    stackSize: 6000

subscribe:
  imuDataTopic: direct
  modeTopic: direct
  

publish:
  - attitudeDeterminationTopic
  - isStableTopic
#  - corfu::appIsAliveTopic
#  - corfu::anomalyTopic
#  - corfu::extendedTelemetryTopic

telecommands:
  NOP:
    id: 1
  SetControlMode:
    id: 2
    fields:
      mode:
        type: uint8_t
        aliases:
          0: Nothing
          1: Position
          2: Velocity
          3: RPM
          4: Step
      submode:
        type: float
        default_value: 2
    description: |
      ### changes the position / velocity of the satellite

      * Noting: keeps the current position
      * Position: aligns the attitude to the in submode specified attitude
      * Velocity: changes the desired velocity to the in submode specified attitude
  SafePowerUpDown:
    id: 3
    description: changes the satellites flywheel from 0 to 2500 RPM and back
    fields: 
      highRPM: uint8_t
  SetPid:
    id: 4
    description: sets the values for the PID controller. this is mostly used during testing, because we don't want to flash the floatsat every time we want to try new values
    fields:
      k_pos:
        array:
          length: 3
          type: float
      k_v_sat:
        array:
          length: 3
          type: float
      k_v_wheel:
        array:
          length: 3
          type: float
          default_value: 2.7 , 0.008, 0



#  ExampleWithFields:
#    id: 2
#    fields:
#      parameter: uint8_t

standard_telemetry:
    attitudeYaw:
      type: float
      customWidget: plottingWidget
    pitch: float
    roll: float
    speed:
      type: float 
      customWidget: plottingWidget
    target_att: 
      type: float 
      customWidget: plottingWidget
    target_speed:
      type: float 
      customWidget: plottingWidget
    target_RPM:
      type: float 
      customWidget: plottingWidget
    motor_speed:
      type: float 
      customWidget: plottingWidget
    power_up: bool
    controlMode: uint8_t


#extended_telemetry:
#  exampleETX:
#    id: 1
#    fields:
#      number: uint8_t

#anomalies:

