id: 0x07
name: pcdu
description: power control and distribution

publish:
  - peripheralOnOffTopic 

telecommands:
  NOP:
    id: 0
  SetOnOff:
    id: 1
    fields:
      powerline:
        type: uint8_t
        aliases:
          0: IMU
          1: Sun Sensors
          2: Raspberry PI
      setOn: bool
  SetState:
    id: 2
    fields:
      state:
        bit_array:
          length: 6 #change this if new things to turn on/off
          aliases:
            0: IMU
            1: Sun Sensor
            2: Raspberry PI

standard_telemetry:
  powerline_states:
    bit_array:
      length: 3 #change here too
    